root: true

extends:
- semistandard
- plugin:prettier/recommended

env:
  node: yes

parserOptions:
  ecmaVersion: 2018
  ecmaFeatures:
    globalReturn: no
    jsx: no

rules:
  strict:
  - error
  - safe

overrides:
  - files:
    - src/**/*.js
    - bin/*
    parserOptions:
      ecmaVersion: 2018
    env:
      browser: no

  - files:
    - doc/**/*.js
    env:
      node: no