language: node_js
node_js: "10"

before_install:
- export TZ=Europe/Oslo

install: npm ci --ignore-scripts

stages:
- lint # lint code and docs
- test # all tests

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test
