## Theme doc:
## https://github.com/pages-themes/minimal

theme: jekyll-theme-minimal
name: NAV-Ally

title: nav-ally
description:
show_downloads: true
logo: /resources/nav-logo.jpg

permalink: pretty
timezone: Europa/Oslo

collections:
  pages:
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
