# Site settings
title: Jekyll Doc Theme
email: your-email@domain.com
description: >
  Jekyll Template for Project Websites
  providing documentation and blog post pages.
lang: en-US

baseurl: "/guide" # the subpath of your site, e.g. /blog/
url: https://navikt.github.io/nav-ally # the base hostname & protocol for your site
git_address: https://github.com/navikt/nav-ally
git_edit_address: https://github.com/navikt/nav-ally/docs

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
