source 'https://rubygems.org'

group :jekyll_plugins do
  gem "github-pages", ">= 198"
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-redirect-from"
  gem "jemoji", ">= 0.10.2"
end

gem "w3c_validators", ">= 1.3.4"
gem "html-proofer", ">= 3.11.0"