#!/usr/bin/env ruby
# frozen_string_literal: true

# A slightly modified version of validate-html from the Github Minimal
# theme that also checks subpages. Original source:
# https://github.com/pages-themes/minimal/blob/master/script/validate-html

require 'w3c_validators'

def validator(file)
  extension = File.extname(file)
  if extension == '.html'
    W3CValidators::NuValidator.new
  elsif extension == '.css'
    W3CValidators::CSSValidator.new
  end
end

def validate(file, folder)
  puts "Checking #{file}..."

  path = File.expand_path "#{folder}/#{file}", __dir__
  results = validator(file).validate_file(path)

  return puts 'Valid!' if results.errors.empty?

  results.errors.each { |err| puts err.to_s }
  exit 1
end

site = './_site'
validate 'index.html', site

Dir.glob('./_site/pages/*.html') do |html_file|
  validate File.basename(html_file), './_site/pages'
end

cssfile = File.join 'assets', 'css', 'style.css'
validate cssfile, site
